config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'about' => 'home#about'
  get 'comics' => 'home#comics'
  get 'gallery' => 'home#gallery'
  get 'photography' => 'home#photography'
  get 'film' => 'home#film'
  get 'contact' => 'home#contact'

  get 'comics#index' => 'comics#index'
  get 'gallery#index' => 'gallery#index'
  get 'photography#index' => 'photography#index'
  get 'film#index' => 'film#index'
  get 'contact/index' => 'contact#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index

  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index

  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index

  end
end

app/controllers/film_controller.rb
class FilmController < ApplicationController
  def index

  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/photography_controller.rb
class PhotograhyController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_footer.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-bottom
  .container-fluid
    .container
      .navbar-header
        %button{:type => 'button', :class => 'navbar-toggle', 'data-toggle' =>'collapse', 'data-target' => '#navbar-collapse'}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'All rights reserved Insatiable', root_url, class: 'navbar-brand'

      #navbar-collapse.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to 'comics', comics_path
          %li
            = link_to 'gallery', gallery_path
          %li
            = link_to 'photography', photography_path
          %li
            = link_to 'film', film_path
          %li
            = link_to 'contact', contact_path

app/views/common/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button{:type => 'button', :class => 'navbar-toggle', 'data-toggle' =>'collapse', 'data-target' => '#navbar-collapse'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Insatiable', root_url, class: 'navbar-brand'

    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'About', about_path
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Work
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              = link_to 'Film', film_path
            %li
              = link_to 'Comics', comics_path
            %li
              = link_to 'Gallery', gallery_path
            %li
              = link_to 'Photography', photography_path
        %li
          = link_to 'Contact', contact_path

app/views/home/about.html.haml
.banner.home-page.top
  %h1 Satisfaction breeds stagnation.
.container
  .container-fluid.top
    %aside Insatiable productions strives to push the boundaries of human creation & inspire others who are insatiable.

app/views/home/comics.html.haml
.banner.home-page.top
  %h1 Comics
.container
  .container-fluid
    = render 'comics/index'
    .grid-container
      %ul.grid
        %li
          %h3
            COMICS
        %li
          %h3
            COMICS
        %li
          %h3
            COMICS
        %li
          %h3
            COMICS
        %li
          %h3
            COMICS
        %li
          %h3
            COMICS

app/views/home/contact.html.haml
.banner.home-page.top
  %h1 Contact
.container
  .container-fluid
    = render 'contact/index'

app/views/home/film.html.haml
.banner.home-page.top
  %h1 Film

.container
  .container-fluid
    = render 'film/index'
    .grid-container
      %ul.grid
        %li
          %h3
            FILM
        %li
          %h3
            FILM
        %li
          %h3
            FILM
        %li
          %h3
            FILM
        %li
          %h3
            FILM
        %li
          %h3
            FILM

app/views/home/gallery.html.haml
.banner.home-page.top
  %h1 Gallery
.container
  .container-fluid
    = render 'gallery/index'
    .grid-container
      %ul.grid
        %li
          %h3
            GALLERY
        %li
          %h3
            GALLERY
        %li
          %h3
            GALLERY
        %li
          %h3
            GALLERY
        %li
          %h3
            GALLERY
        %li
          %h3
            GALLERY

app/views/home/index.html.haml
.banner.home-page.top
  %h1 Welcome to the Insatiable

.container
  .container-fluid
    .grid-container
      %ul.grid
        %a{ :href => film_path }
          %li
            %h3
              FILM
        %a{ :href => comics_path }
          %li
            %h3
              COMICS
        %a{ :href => gallery_path }
          %li
            %h3
              GALLERY
        %a{ :href => photography_path }
          %li
            %h3
              PHOTOGRAPHY

app/views/home/photography.html.haml
.banner.home-page.top
  %h1 Photography
.container
  .container-fluid
    = render 'photography/index'
    .grid-container
      %ul.grid
        %li
          %h3
            PHOTOGRAPHY
        %li
          %h3
            PHOTOGRAPHY
        %li
          %h3
            PHOTOGRAPHY
        %li
          %h3
            PHOTOGRAPHY
        %li
          %h3
            PHOTOGRAPHY
        %li
          %h3
            PHOTOGRAPHY

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <title>Insatiable</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= tag('meta', :name => 'viewport', :content => 'width=device-width, initial-scale=1, maximum-scale=1 ') %>
  </head>
  <body>
    <%= render 'common/header' %>
    <%= yield %>
    <!--<%= render 'common/footer' %>-->
  </body>
</html>